"""create bidders documents portal_responses compliance_results audit_log tables

Revision ID: bd589460ecc1
Revises: 
Create Date: 2026-09-10 03:27:57.945172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd589460ecc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('curr_hash', sa.String(), nullable=False),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('bidders',
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('company_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_REVIEW', 'VERIFIED', 'REJECTED', name='bidder_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bidder_id')
    )
    op.create_table('compliance_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PASS', 'FAIL', 'NEEDS_REVIEW', name='requirement_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('risk_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.bidder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('documents',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', postgresql.ENUM('UDYAM_CERTIFICATE', 'GST_CERTIFICATE', 'PAN_CARD', 'EPFO_CHALLAN', 'MCA21_CERTIFICATE', 'STARTUP_INDIA_CERT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.bidder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('portal_responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('portal_name', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'NOT_FOUND', 'UNAVAILABLE', 'ERROR', name='portal_status'), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.bidder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portal_responses')
    op.drop_table('documents')
    op.drop_table('compliance_results')
    op.drop_table('bidders')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
